### ISSUE TITLE
Obtain document-topic representation after training?

### ISSUE THREAD

**Issue by bwang482** [jhlau/topically-driven-language-model#1]
Hi jhlau, thanks for sharing your implementation.

I wonder where can I obtain the document-topic representation learnt during training for the training documents (in a unsupervised setting)? I don't necessarily want to infer topic distribution for some unseen documents in this case as I only need a unsupervised way to learn document representation that embeds topic information.

Thanks!

**Comment by jhlau** [comment]
You'll have to infer the topic distribution for the training documents unfortunately, as the model doesn't really keep track of them unlike LDA models (which stores them in a matrix).

In theory you can explicitly 'save' the inferred topic distribution during training, and I've thought of doing it, but it's bad for two reasons:
-the topic distribution learnt for the first batch could be different to the last batch, as the model is still changing
-it won't scale well memory wise for very large document collection
