### ISSUE TITLE
Compute the perplexity on testing data but get "ZeroDivisionError: float division by zero"

### ISSUE THREAD

**Issue by JiangYanting** [jhlau/topically-driven-language-model#10]
Hello! I have trained a toy_model using training data, but when I computed the perplexity on testing data,  I got an error:
`Documents statistics:
        no. of docs = 701
        language model no. of sequences = 1416
        language model no. of tokens = 30958
        original sent mean len = 44.16262482168331
        original sent max len = 757
        original sent min len = 2
Traceback (most recent call last):
  File "/home/jiangyanting/topically-driven-language-model-python3/tdlm_test.py", line 261, in <module>
    run_epoch(sents, docs, tags, (tm, lm), vocabxid[pad_symbol], cf, idxvocab)
  File "/home/jiangyanting/topically-driven-language-model-python3/tdlm_test.py", line 94, in run_epoch
    print("\ntest topic model perplexity = %.3f" % (np.exp(tm_costs/tm_words)))
ZeroDivisionError: float division by zero`

  I guess this is because there exist some new words in testing data, however these words are not in train data ? So Could you please help me deal with this problem ? thank you so much !

**Comment by jhlau** [comment]
Looks like tm_words might be zero here, and tm_words is the total number of words in your test data. You should look into it why tm_words=0. Don't think I can help much beyond that.

**Comment by JiangYanting** [comment]
@jhlau  Thanks for your instruction ! I have found that my parameter "tm_num_batches" is always zero, and I didn't provide the pre-trained word embedding when training the model. Could this error be caused due to the absence of pre-trained word embedding ?

**Comment by jhlau** [comment]
Don't think that's the problem. The pre-trained word embedding is only used for training.

**Comment by JiangYanting** [comment]
@jhlau  Well, I have used the standard training and testing data in your github ,and it can compute the perplexity. Maybe this error is because of my data format, I would have another try.
  And by the way, **where could I find the file which contains the probability distribution of "Topic-words" ? That is "p(words | topic) "**. Thanks for your reply !

**Comment by jhlau** [comment]
It's not stored anywhere (it's in the saved model binary), but you can see how to get the topic words here: https://github.com/jhlau/topically-driven-language-model/blob/master/tdlm_model.py#L146

**Comment by JiangYanting** [comment]
@jhlau  I got it,thank you very much!
