### ISSUE TITLE
Can TDLM do incremental training ?

### ISSUE THREAD

**Issue by JiangYanting** [jhlau/topically-driven-language-model#11]
Hello ! I'm wondering whether TDLM can do incremental training ? In other words, after I trained a model using corpus A,  Could I further update the parameters in this model using corpus B ? thanks !
  Best regards.

**Comment by jhlau** [comment]
Not at the moment, no. To do you'd need to update the code (not hard; you can modify tdlm_test and make it continue train on another corpus).

**Comment by JiangYanting** [comment]
@jhlau  I got it. I would have a try~ ^_^
