### ISSUE TITLE
what's the meaning of hyper-parameter "tm_sent_len"?

### ISSUE THREAD

**Issue by JiangYanting** [jhlau/topically-driven-language-model#12]
Hello, I am a little confused about the hyper-parameters "**tm_sent_len**"(default value is 3 ) and "**lm_sent_len**" (default value is 30) .
  Although I have read your ACL paper, knowing that "**tm_sent_len**" is "Output sequence length for topic model",  lm_sent_len is **Sequence length for language model** , I'm still not so clear what is the specific meaning of "Output sequence length for topic model" and "Sequence length for language model"..... _(:」∠)_ thank you very much!

**Comment by jhlau** [comment]
tm_sent_len = Output sequence length for topic model = we predict 3 words at a time for TM
lm_sent_len = Sequence length for language model = we predict a sequence of 30 words for LM (it's the sentence length)

**Comment by JiangYanting** [comment]
@jhlau  oh I got it ! thanks !
             Best regards.
