### ISSUE TITLE
Can I train the model using GPU

### ISSUE THREAD

**Issue by JiangYanting** [jhlau/topically-driven-language-model#13]
I attempted to train a model  using a 120MB training data (txt format), but my server didn't run the GPU and it went so slowly. So can I do training using GPU? Thanks ╰(*´︶`*)╯

**Comment by jhlau** [comment]
You can yeap. Have a look at the tensorflow documentation how to use GPUs for training. The code doesn't change (but there are changes you may need to make at the script level to run the code).

**Comment by JiangYanting** [comment]
@jhlau  I have managed to use a GPU, and it growed faster, thanks !
