### ISSUE TITLE
word topic representation

### ISSUE THREAD

**Issue by xinlux97** [jhlau/topically-driven-language-model#15]
Hi jhlau, thanks for sharing your implementation.

You've provided way to obtain the document-topic representation, but I wonder where can I obtain the word-topic representation? For example if there are 128 topics, each word-topic representation has length=128, and all word-topic representations are saved in a vocab file of something like that.

Thanks!

**Comment by jhlau** [comment]
--output_topic argument from tdlm_test.py will do the job.

**Comment by xinlux97** [comment]
> --output_topic argument from tdlm_test.py will do the job.

Hi,
I see this argument in  tdlm_test.py
`parser.add_argument("--output_topic", help="output file to save the topics (prints top-N words of each topic)")`
It's like this argument will print relevant words for each topic. The word-topic representation for one word should be a vector with length=num_topics. And if the vocabulary contains n words, I'm expecting a matrix with dim= (n, num_topics) as the word-topic representation.

**Comment by jhlau** [comment]
I see. You'll have to modify the code to get word-topic distribution. You can see how topic-word is generated here: https://github.com/jhlau/topically-driven-language-model/blob/master/tdlm_model.py#L146 (you'll need to transpose the matrix before you do the softmax at line 149, so you get a probability distribution over topics for each word).
