### ISSUE TITLE
Update to Tensorflow 1.3

### ISSUE THREAD

**Issue by GabrielLin** [jhlau/topically-driven-language-model#5]
I try to update the code into TF 1.3 using official tf_upgrade.py and modify some module manually.  The linear function in tdlm_model.py does not exist in TF 1.3 anymore. I try to replace it with rnn_cell_impl._linear . But it does not work. 

Could you please help to update the code to higher TF version. Thanks.

**Comment by jhlau** [comment]
Hi, unfortunately I don't use TF1.3 so won't be providing support for the upgrade. You can technically copy the linear function if that's the only issue. Happy to create a branch for TF1.3 if you want to make a PR.
